uzun=int(input('uzun kenarın uzunluğunu giriniz'))
print(uzun)
kisa=int(input('kısa kenarın uzunlugunu giriniz'))
print(kisa)
cevre = 2*(kisa +uzun)
print('cevre',cevre)
alan =(kisa*uzun)
print('alan',alan)
